'use strict';
(async () => {
  const results = [];
  const assert = (condition, label) => { if (!condition) throw new Error(label); results.push(label); };
  async function rejects(fn, label) {
    let rejected = false;
    try { await fn(); } catch { rejected = true; }
    assert(rejected, label);
  }
  function mockStorage(initial = {}) {
    const data = { local: structuredClone(initial), sync: {}, session: {} };
    const access = {};
    let failWrites = false;
    let failCleanup = false;
    let failLocalWrites = false;
    const storage = Object.fromEntries(Object.keys(data).map(area => [area, {
      async setAccessLevel(value) { access[area] = value.accessLevel; },
      async get(key) { return structuredClone(key === null ? data[area] : Object.hasOwn(data[area], key) ? { [key]: data[area][key] } : {}); },
      async set(patch) { if (area === 'local' && failLocalWrites) throw new Error('local write failed'); if (area === 'sync' && failWrites) throw new Error('quota'); Object.assign(data[area], structuredClone(patch)); },
      async remove(key) { if (area === 'local' && failCleanup) throw new Error('cleanup failed'); delete data[area][key]; }
    }]));
    return { storage, data, access, fail: value => { failWrites = value; }, failCleanup: value => { failCleanup = value; }, failLocal: value => { failLocalWrites = value; } };
  }
  const passphrase = 'test only four random words 9842';
  try {
    const mock = mockStorage({ urlMappings: { GitHub: 'https://github.com', '__proto__': 'https://example.com' } });
    const vault = Vault.create(mock.storage);
    await rejects(() => vault.run('add', { keyword: 'test', url: 'https://example.com' }), 'Locked writes rejected');
    await vault.run('setup', { passphrase, confirmation: passphrase });
    assert(Object.values(mock.access).every(value => value === 'TRUSTED_CONTEXTS'), 'All storage restricted to trusted contexts');
    assert(!mock.data.local.urlMappings, 'Successful migration removes legacy plaintext');
    assert((await vault.run('list')).github === 'https://github.com', 'Legacy keyword normalized and migrated');
    assert(!JSON.stringify(mock.data.sync).includes('github') && !JSON.stringify(mock.data.sync).includes(passphrase), 'Persistent sync contains neither keyword, URL nor passphrase');
    await rejects(() => vault.run('add', { keyword: 'github', url: 'https://other.example' }), 'Duplicate add preserves destination');
    await rejects(() => vault.run('add', { keyword: 'bad', url: 'javascript:alert(1)' }), 'Script URLs rejected');
    await rejects(() => vault.run('add', { keyword: 'bad', url: 'https://name:password@example.com' }), 'Credential-bearing URLs rejected');
    await rejects(() => vault.run('add', { keyword: 'bad\u202etest', url: 'https://example.com' }), 'Bidi control characters rejected');
    for (const address of ['http://intranet', 'http://192.168.1.10', 'http://localhost:8080']) {
      await vault.run('add', { keyword: 'internal', url: address });
      assert((await vault.run('list')).internal === address, `Internal HTTP supported: ${address}`);
      await vault.run('remove', { keyword: 'internal' });
    }
    await rejects(() => vault.run('add', { keyword: 'bad', url: 'https:example.com' }), 'Ambiguous URL shorthand rejected');
    await rejects(() => vault.run('add', { keyword: 'bad', url: 'https://example.com\\path' }), 'Backslash URL ambiguity rejected');
    await vault.run('add', { keyword: '__proto__', url: 'https://example.com/prototype' });
    assert(Object.hasOwn(await vault.run('list'), '__proto__'), 'Prototype-like keywords stored safely');
    await Promise.all(['first', 'second'].map(keyword => vault.run('add', { keyword, url: 'https://example.com' })));
    assert(Object.keys(await vault.run('list')).length === 4, 'Concurrent adds serialized without lost entries');
    const before = JSON.stringify(mock.data.sync);
    await rejects(() => vault.run('import', { text: '{"okay":"https://example.com","bad":"data:text/html,no"}' }), 'Invalid import rejected as a whole');
    assert(JSON.stringify(mock.data.sync) === before, 'Invalid import leaves vault unchanged');
    const imported = await vault.run('import', { text: '{"github":"https://other.example","new":"https://new.example"}' });
    assert(imported.added === 1 && imported.skipped === 1 && (await vault.run('list')).github === 'https://github.com', 'Import preserves existing destinations');
    await rejects(() => vault.run('import', { text: 'null' }), 'Null import rejected');
    await rejects(() => vault.run('import', { text: 'x'.repeat(1048577) }), 'Oversized import rejected');
    const backup = await vault.run('export');
    assert(!JSON.stringify(backup).includes('https://'), 'Backups contain only encrypted destinations');
    assert(!JSON.stringify(backup).includes(mock.data.local.vaultKey.raw), 'Backup excludes persistent unlock key');
    assert(!JSON.stringify(mock.data.sync).includes(mock.data.local.vaultKey.raw), 'Sync excludes persistent unlock key');
    const records = Object.keys(mock.data.sync).filter(key => key.startsWith('site.'));
    const record = structuredClone(mock.data.sync[records[0]]);
    mock.data.sync[records[0]].data = (record.data[0] === 'A' ? 'B' : 'A') + record.data.slice(1);
    await rejects(() => vault.run('list'), 'Ciphertext tampering fails authentication');
    mock.data.sync[records[0]] = record;
    mock.data.sync[records[1]] = record;
    await rejects(() => vault.run('list'), 'Moving ciphertext between record IDs fails authentication');
    mock.data.sync = structuredClone(backup.data);
    await vault.run('lock');
    assert(!mock.data.local.vaultKey, 'Forget device removes persistent unlock key');
    await rejects(() => vault.run('list'), 'Locked vault cannot be read');
    await rejects(() => vault.run('unlock', { passphrase: 'incorrect passphrase 1234' }), 'Wrong passphrase rejected');
    assert(!mock.data.local.vaultKey, 'Wrong passphrase never retained');
    await vault.run('unlock', { passphrase });
    assert(Object.keys(await vault.run('list')).length === 5, 'Correct passphrase restores library');
    const device2 = mockStorage();
    device2.data.sync = structuredClone(mock.data.sync);
    const second = Vault.create(device2.storage);
    assert(!(await second.run('state')).unlocked, 'Synced device starts locked');
    await second.run('unlock', { passphrase });
    assert((await second.run('list')).github === 'https://github.com', 'Second device decrypts synced sites with same passphrase');
    await second.run('remove', { keyword: 'github' });
    assert(!Object.hasOwn(await second.run('list'), 'github'), 'Removal deletes only selected encrypted record');
    const fresh = mockStorage();
    const restored = Vault.create(fresh.storage);
    const newPassphrase = 'another test passphrase for new vault';
    await restored.run('setup', { passphrase: newPassphrase, confirmation: newPassphrase });
    await restored.run('import', { text: JSON.stringify(backup), passphrase });
    assert((await restored.run('list')).github === 'https://github.com', 'Backup restored into a different vault and re-encrypted');
    const failure = mockStorage({ urlMappings: { original: 'https://original.example' } });
    failure.fail(true);
    await rejects(() => Vault.create(failure.storage).run('setup', { passphrase, confirmation: passphrase }), 'Failed sync write reported');
    assert(failure.data.local.urlMappings.original === 'https://original.example', 'Failed migration preserves original plaintext');
    await rejects(() => Promise.resolve(Vault.quota({ long: 'x'.repeat(8192) })), 'Per-item quota enforced');
    await rejects(() => Promise.resolve(Vault.quota(Object.fromEntries(Array.from({length:513}, (_,i) => [String(i), 'x'])))), 'Item-count quota enforced');
    await rejects(() => Promise.resolve(Vault.quota(Object.fromEntries(Array.from({length:100}, (_,i) => [String(i), 'x'.repeat(1100)])))), 'Total quota enforced');
    const migration = mockStorage({urlMappings:{github:'https://different.example'}});
    migration.data.sync = structuredClone(backup.data);
    const migrating = Vault.create(migration.storage);
    migration.failCleanup(true);
    const migrationResult = await migrating.run('unlock',{passphrase});
    assert(!!migrationResult.warning && !!migration.data.local.urlMappings, 'Cleanup failure retains local data and shows warning');
    const migrated = await migrating.run('list');
    assert(migrated.github === 'https://github.com' && migrated['github-local-1'] === 'https://different.example', 'Cross-device legacy conflicts preserved with renamed local keyword');
    const migrationCount = Object.keys(migrated).length;
    migration.failCleanup(false);
    await migrating.run('lock');
    await migrating.run('unlock', {passphrase});
    assert(Object.keys(await migrating.run('list')).length === migrationCount, 'Migration retry does not duplicate renamed conflicts');
    assert(!migration.data.local.urlMappings, 'Migration retry finishes local cleanup');
    mock.data.session = {};
    const restarted = Vault.create(mock.storage);
    assert((await restarted.run('state')).unlocked, 'Browser restart preserves device unlock');
    assert((await restarted.run('list')).github === 'https://github.com', 'Restarted worker decrypts sites without passphrase');
    mock.data.session.vaultKey = mock.data.local.vaultKey;
    delete mock.data.local.vaultKey;
    assert((await Vault.create(mock.storage).run('state')).unlocked, 'Upgrade preserves a previous session unlock');
    assert(!!mock.data.local.vaultKey && !mock.data.session.vaultKey, 'Upgrade migrates key to local-only persistent storage');
    const changedVault = mockStorage();
    changedVault.data.sync = structuredClone(fresh.data.sync);
    changedVault.data.local.vaultKey = structuredClone(mock.data.local.vaultKey);
    assert(!(await Vault.create(changedVault.storage).run('state')).unlocked, 'A different vault cannot use a stale device key');
    const validKey = structuredClone(mock.data.local.vaultKey);
    mock.data.local.vaultKey.raw = 'not base64!';
    assert(!(await restarted.run('state')).unlocked, 'Malformed saved key shows unlock instead of trapping the UI');
    await rejects(() => restarted.run('list'), 'Malformed saved key cannot expose sites');
    await restarted.run('unlock', {passphrase});
    assert((await restarted.run('list')).github === 'https://github.com', 'Passphrase repairs a malformed saved key');
    mock.data.local.vaultKey.raw = btoa(String.fromCharCode(...new Uint8Array(64)));
    assert(!(await restarted.run('state')).unlocked, 'Wrong saved key fails authentication and requests unlock');
    mock.data.local.vaultKey = validKey;
    mock.data.session.vaultKey = structuredClone(validKey);
    await restarted.run('lock');
    assert(!mock.data.local.vaultKey && !mock.data.session.vaultKey, 'Forget device removes both current and legacy key copies');
    assert(!(await Vault.create(mock.storage).run('state')).unlocked, 'Forgotten key cannot reappear from legacy session storage');
    mock.data.local = {};
    mock.data.session = {};
    assert(!(await Vault.create(mock.storage).run('state')).unlocked, 'Reinstallation requires unlock even after encrypted sync returns');
    const editing = mockStorage();
    const editable = Vault.create(editing.storage);
    await rejects(() => editable.run('setup', {passphrase:'1234567', confirmation:'1234567'}), 'Seven-character passphrase rejected');
    await editable.run('setup', {passphrase:'eight888', confirmation:'eight888'});
    await editable.run('add', {keyword:'internal', url:'http://intranet'});
    await editable.run('update', {keyword:'internal', url:'http://localhost:8080', expectedUrl:'http://intranet'});
    assert((await editable.run('list')).internal === 'http://localhost:8080', 'Inline update preserves keyword and changes URL');
    await rejects(() => editable.run('update', {keyword:'internal', url:'https://stale.example', expectedUrl:'http://intranet'}), 'Stale edit rejected without overwriting a newer URL');
    await rejects(() => editable.run('update', {keyword:'internal', url:'javascript:alert(1)', expectedUrl:'http://localhost:8080'}), 'Unsafe edited URL rejected');
    await rejects(() => editable.run('update', {keyword:'removed', url:'https://example.com', expectedUrl:'https://example.com'}), 'Editing a removed site cannot recreate it');
    const oldExport = await editable.run('export');
    const oldData = JSON.stringify(editing.data.sync);
    await rejects(() => editable.run('changePassphrase', {currentPassphrase:'wrong888', passphrase:'newpass8', confirmation:'newpass8'}), 'Passphrase change requires correct current passphrase');
    await rejects(() => editable.run('changePassphrase', {currentPassphrase:'eight888', passphrase:'newpass8', confirmation:'mismatch'}), 'Passphrase confirmation enforced');
    editing.fail(true);
    await rejects(() => editable.run('changePassphrase', {currentPassphrase:'eight888', passphrase:'newpass8', confirmation:'newpass8'}), 'Failed rotation write reported');
    assert(JSON.stringify(editing.data.sync) === oldData, 'Failed rotation leaves original encrypted library intact');
    editing.fail(false);
    const remembered = structuredClone(editing.data.local.vaultKey);
    await editable.run('changePassphrase', {currentPassphrase:'eight888', passphrase:'newpass8', confirmation:'newpass8'});
    assert((await editable.run('list')).internal === 'http://localhost:8080', 'Passphrase rotation preserves sites and current device unlock');
    assert(editing.data.local.vaultKey.raw !== remembered.raw, 'Passphrase change rotates encryption material');
    assert(atob(editing.data.local.vaultKey.raw).slice(32) !== atob(remembered.raw).slice(32), 'Rotation replaces the identifier key for future keywords');
    await editable.run('update', {keyword:'internal', url:'http://localhost:8081', expectedUrl:'http://localhost:8080'});
    await editable.run('update', {keyword:'internal', url:'http://localhost:8080', expectedUrl:'http://localhost:8081'});
    assert(Object.keys(await editable.run('list')).length === 1, 'Editing after key rotation reuses the existing record');
    assert(Object.keys(editing.data.sync).sort().join() === Object.keys(oldExport.data).sort().join(), 'Rotation replaces records in place without leaving old ciphertext records');
    const other = mockStorage(); other.data.sync = structuredClone(editing.data.sync); other.data.local.vaultKey = remembered;
    const otherDevice = Vault.create(other.storage);
    assert(!(await otherDevice.run('state')).unlocked, 'Other devices require new passphrase after rotation');
    await rejects(() => otherDevice.run('unlock', {passphrase:'eight888'}), 'Old passphrase cannot unlock rotated library');
    await otherDevice.run('unlock', {passphrase:'newpass8'});
    assert((await otherDevice.run('list')).internal === 'http://localhost:8080', 'Eight-character new passphrase unlocks synced library');
    await editable.run('remove', {keyword:'internal'});
    await rejects(() => editable.run('import', {text:JSON.stringify(oldExport), passphrase:'newpass8'}), 'Older backup rejects the replacement passphrase');
    await editable.run('import', {text:JSON.stringify(oldExport), passphrase:'eight888'});
    assert((await editable.run('list')).internal === 'http://localhost:8080', 'Older backup restores using its original passphrase');
    const originalSyncGet = editing.storage.sync.get;
    const recordName = Object.keys(editing.data.sync).find(name => name.startsWith('site.'));
    const beforeConflict = structuredClone(editing.data.sync);
    let reads = 0;
    editing.storage.sync.get = async key => {
      if (key === null && ++reads === 2) delete editing.data.sync[recordName];
      return originalSyncGet(key);
    };
    await rejects(() => editable.run('update', {keyword:'internal', url:'http://intranet/new', expectedUrl:'http://localhost:8080'}), 'Deletion arriving during encryption is not overwritten');
    assert(!editing.data.sync[recordName], 'Late synced deletion remains deleted');
    editing.storage.sync.get = originalSyncGet;
    editing.data.sync = beforeConflict;
    editing.failLocal(true);
    const rotatedWithoutLocal = await editable.run('changePassphrase', {currentPassphrase:'newpass8', passphrase:'third888', confirmation:'third888'});
    assert(!!rotatedWithoutLocal.warning, 'Local-key write failure after rotation provides recovery instructions');
    assert(!(await editable.run('state')).unlocked, 'Stale device key cannot open rotated data after local write failure');
    editing.failLocal(false);
    await editable.run('unlock', {passphrase:'third888'});
    assert((await editable.run('list')).internal === 'http://localhost:8080', 'New passphrase recovers rotation when saving local key failed');
    const onboarding = mockStorage();
    const newcomer = Vault.create(onboarding.storage);
    assert((await newcomer.run('state')).onboardingChoice === null, 'Fresh install does not assume a new or existing user');
    await newcomer.run('chooseOnboarding', {choice:'existing'});
    assert((await Vault.create(onboarding.storage).run('state')).onboardingChoice === 'existing', 'Existing-user choice survives popup and worker restarts');
    await rejects(() => newcomer.run('setup', {passphrase:'fresh888', confirmation:'fresh888'}), 'Existing-user waiting path cannot create a replacement vault');
    assert(Object.keys(onboarding.data.sync).length === 0, 'Waiting for sync writes no new vault');
    onboarding.data.sync = structuredClone(editing.data.sync);
    assert((await newcomer.run('state')).configured, 'Late synced vault becomes available without new setup');
    await newcomer.run('unlock', {passphrase:'third888'});
    assert((await newcomer.run('list')).internal === 'http://localhost:8080', 'Existing passphrase unlocks sites on the second machine');
    await rejects(() => newcomer.run('chooseOnboarding', {choice:'unknown'}), 'Invalid onboarding choices rejected');
    document.getElementById('results').textContent = `${results.length} checks passed\n\n${results.join('\n')}`;
    document.body.dataset.result = 'passed';
  } catch (error) {
    document.getElementById('results').textContent = `${results.length} checks passed before failure\n${error.stack}`;
    document.body.dataset.result = 'failed';
  }
})();
